[package]
name = "corevm-codec-wasm"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "CoreVM codec collection. Used to encode and decode output streams produced by the guest."
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
corevm-codec.workspace = true
jam-codec.workspace = true
js-sys = "0.3.91"
wasm-bindgen = "0.2.114"

[package.metadata.wasm-pack.profile.release]
# https://github.com/drager/wasm-pack/issues/1441#issuecomment-2886461752
wasm-opt = ["-O", "--enable-bulk-memory"]
