[package]
name = "corevm-codec-bench"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
description = "CoreVM codec benchmark"
publish = false

[features]
default = ["corevm"]
corevm = []
qoi = ["dep:qoi"]
av1 = ["dep:rav1e"]

[lints]
workspace = true

[dependencies]
corevm-codec = { workspace = true, features = ["std", "stats"] }
qoi = { version = "0.4.1", optional = true }
rav1e = { version = "0.7.1", default-features = false, features = ["asm"], optional = true }
