---
name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Run tests
        run: ./ci/test.sh
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Run benchmarks (CoreVM)
        run: ./ci/bench.sh
